services:
  webhook-listener:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ~/deploy-data:/deploy  # Only keep this bind mount
    environment:
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    networks:
      - ssl_default
    restart: unless-stopped

networks:
  ssl_default:
    external: true