version: '3.8'

services:
  webhook-listener:
    build: .
    container_name: webhook-listener
    networks:
      - ssl_default
    expose:
      - "8000"
    environment:
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
    volumes:
      - deploy-data:/deploy
    restart: unless-stopped

volumes:
  deploy-data:

networks:
  ssl_default:
    external: true 
